<script setup lang="ts">
const route = useRoute()

const config = useRuntimeConfig()

const { data : users, error } = await useAsyncData(`user-${route.params.id}`, async () => {
  const { data } = await $fetch<APIReseponse<Users>>(
    `${config.public.apiUrl}/api/users/${route.params.id}`
  )
  return data
})
if (!users.value || error.value) {
  throw new Error('User not found')
}
</script>

<template>
  <div class="uniqueUserPage">
    <h1 class="uniqueUserPage__title">{{ users?.username }}</h1>
    <p class="uniqueUserPage__texte">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel porttitor lectus. Nam varius metus mi, ac dictum ipsum malesuada sit amet. In consequat velit tellus, at malesuada turpis porttitor sed. Curabitur eu convallis nisl. Donec nec rhoncus nulla. Suspendisse non egestas dui, tincidunt egestas risus. Cras rhoncus mi sit amet scelerisque ullamcorper.
      Fusce id facilisis lacus, in iaculis nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper est et gravida dictum. Suspendisse aliquam nulla non ligula scelerisque pharetra. Nullam consectetur eu odio ac ultricies. Nam iaculis magna mi, ac commodo sapien ullamcorper vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis id metus congue, imperdiet justo nec, ornare ipsum. Aliquam condimentum posuere aliquet.
      Phasellus in dignissim augue. Aliquam blandit semper enim, ut consequat elit volutpat at. Pellentesque facilisis sed urna eu mattis. Suspendisse eu libero neque. Suspendisse sit amet mi rutrum, consequat dui at, venenatis elit. Morbi consequat rhoncus ipsum. Integer quis enim sit amet nibh feugiat accumsan. Integer a consectetur leo, eu ultrices diam. Maecenas sollicitudin sapien nulla, id cursus libero congue ornare. Curabitur rhoncus sodales tempus. Praesent at est mauris. Duis placerat accumsan dui, vel sollicitudin tellus laoreet in.
      Quisque rhoncus ante a ante volutpat, a dictum orci porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae eleifend leo. Pellentesque a odio sed augue sagittis laoreet at et metus. Pellentesque feugiat metus at egestas semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed finibus blandit purus quis aliquam. Donec mollis erat vitae est ultricies efficitur. Nam orci nulla, pretium at diam ut, ullamcorper pellentesque sem. Nullam in lectus odio. Sed a arcu aliquet, varius tellus a, convallis sapien. Pellentesque scelerisque justo nibh, eget tempor est fermentum at. Ut eget ultricies diam.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam in gravida ligula. Fusce vulputate eros ac rhoncus vehicula. Curabitur quis efficitur nisl, at volutpat felis. Nullam in libero eu ante porta efficitur in et sapien. Sed congue, erat eu gravida egestas, quam sapien auctor sapien, eget tristique erat mauris a lorem. Sed egestas nunc et eros mattis, at facilisis dui rutrum. Aenean rhoncus velit non odio mollis, accumsan aliquam leo rutrum. Curabitur nisl massa, posuere ac dolor vitae, malesuada fermentum nibh. Duis sit amet diam eget ligula rutrum eleifend. Suspendisse ornare dolor ut odio varius vestibulum. Duis id libero sed neque tincidunt volutpat. Aenean suscipit dolor nibh, non dapibus ipsum ornare ut. Cras nec semper ligula, nec aliquet odio. Ut sapien felis, facilisis ac pharetra sed, pellentesque vel sem. Morbi id dolor ornare urna dictum condimentum sed a leo.
      Integer non massa sed enim finibus efficitur. Nunc fermentum felis quis ultrices laoreet. Vivamus eget ante ligula. Cras felis urna, accumsan eget nibh a, pharetra ullamcorper augue. Fusce malesuada felis ante, sed auctor ante commodo commodo. Aliquam erat volutpat. Integer convallis aliquam sem. Cras eget finibus metus. In a tempor lacus. In nibh sem, mattis eu nibh vitae, vehicula scelerisque tortor. Pellentesque lectus dolor, tristique quis urna et, auctor consectetur lacus.
      Aenean lacinia sapien vel accumsan ultrices. Vestibulum gravida pharetra mollis. Maecenas interdum, sapien sit amet gravida vehicula, odio sapien interdum nisi, non feugiat tortor dolor sed dolor. Fusce vitae luctus felis. Pellentesque pellentesque, lorem in sagittis bibendum, sem diam euismod justo, in interdum lacus leo ut tellus. Nunc ultrices posuere dui, quis euismod sem maximus eleifend. Nunc ut suscipit tortor. Integer finibus, mauris et rutrum accumsan, orci sem molestie neque, nec egestas odio massa nec velit. Aliquam ullamcorper ante nec nibh iaculis iaculis. Donec accumsan et nunc et elementum. Nullam venenatis fringilla metus sed suscipit. Suspendisse potenti. Morbi auctor enim leo, non faucibus elit venenatis vel. Nunc sodales euismod lectus, in varius ante. Suspendisse faucibus nulla et dui pretium, non maximus enim venenatis.
      Morbi euismod, elit in gravida tincidunt, lorem mauris porttitor tellus, nec laoreet est neque vitae libero. Nullam velit leo, ornare sit amet sapien at, commodo laoreet tellus. In ultricies, eros nec molestie dapibus, urna odio mattis est, vel dignissim mauris dolor quis leo. Aenean scelerisque non neque eget sodales. Praesent hendrerit auctor sapien, a tempus nisl rhoncus non. Etiam dui leo, malesuada in dui ut, pellentesque posuere diam. Nunc ac sapien vestibulum, tempus velit sed, lobortis ligula. Praesent eget arcu non ligula aliquet interdum at vitae magna. Phasellus eget urna et magna ullamcorper condimentum. Ut augue arcu, commodo nec nunc posuere, convallis feugiat elit. Vivamus pulvinar porta lectus facilisis dignissim. Donec elementum, dolor tempor consectetur varius, augue augue blandit turpis, id condimentum nisl lorem gravida augue.
      Suspendisse aliquet eros ut lobortis lacinia. Quisque mollis, risus at efficitur tempus, orci lectus pretium diam, at porttitor sapien neque a mi. Curabitur et tortor sed ex rutrum finibus. Ut massa neque, tristique a pellentesque at, posuere vitae dui. Duis aliquet malesuada sem, sed commodo quam maximus quis. Ut vel pharetra diam, in mollis mi. Sed posuere scelerisque lacinia. Aliquam vestibulum facilisis nisl, in eleifend odio auctor vitae. Vivamus efficitur eros dui, id convallis nisi imperdiet quis. Nulla iaculis auctor dolor quis convallis. Etiam dolor lorem, suscipit in commodo in, tempor in nibh. Fusce nec finibus massa, malesuada aliquet mi.
      Nulla ac facilisis nulla. Quisque sagittis leo ligula, in maximus felis scelerisque in. Sed quam purus, molestie sit amet metus nec, cursus feugiat turpis. Aenean gravida condimentum massa sed tincidunt. Duis ut efficitur orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc non tincidunt nisl. Integer tempus placerat arcu mattis luctus. Donec commodo diam quis elementum efficitur. Ut euismod tellus at ex rutrum, nec dignissim est aliquet. Morbi non arcu dolor.
      Duis in convallis dolor, eu fermentum sem. Mauris sodales pharetra arcu in varius. Curabitur ornare, magna ut aliquam pellentesque, magna tellus congue lectus, vel sodales odio libero vel lorem. Nullam risus erat, placerat sed nibh in, pretium efficitur metus. Donec et pretium velit, eleifend consequat dolor. Quisque sollicitudin ornare augue, quis fringilla elit tincidunt accumsan. Morbi malesuada non mauris sit amet feugiat. Sed condimentum tellus et mauris mollis, id placerat mi dictum. Phasellus blandit facilisis justo, vehicula pulvinar libero sodales nec. Cras dignissim sollicitudin nisl, eu ultricies elit posuere non. Morbi quis pharetra arcu, et ornare turpis. Suspendisse potenti. Nulla euismod tortor lectus, finibus sollicitudin lorem posuere at. Mauris vel nulla id est varius rutrum. Duis imperdiet eu nunc quis sollicitudin. Aenean aliquam libero vitae commodo tempor.
      Cras ultricies lorem metus, ac rhoncus tortor malesuada nec. Duis et fermentum nibh. Quisque sodales, lectus sit amet ullamcorper ornare, lacus nisi aliquet dolor, tincidunt gravida libero diam auctor nunc. Suspendisse tristique eu ipsum auctor malesuada. Nunc a nisi vel elit vulputate mollis. Nam dui enim, vehicula non tincidunt vehicula, auctor in urna. Sed sit amet justo ultricies, viverra diam vitae, eleifend tellus. Donec semper congue sem, ac scelerisque tortor eleifend id. Maecenas sit amet urna nec leo fermentum mattis eget at ex.
      Morbi enim diam, ultricies a enim ut, porta blandit lorem. Aliquam vulputate fringilla porta. Ut ultrices at nibh et molestie. Donec ut justo eros. Aenean porttitor, eros ac vehicula ullamcorper, sem nisi mollis diam, a condimentum leo purus vulputate augue. Maecenas eu metus velit. Fusce pretium, ex vitae vestibulum ultricies, nunc nulla feugiat elit, a sollicitudin urna nisi in mi.
      Suspendisse ut pharetra odio. Aliquam rhoncus quis sapien et pulvinar. Nunc purus urna, lobortis sed felis at, tempor sodales arcu. Curabitur sed elementum sapien. Fusce ipsum sem, consectetur eu ornare in, placerat vel odio. Integer facilisis at felis ac lobortis. Pellentesque quis leo dignissim, convallis urna at, maximus tortor. Duis magna ex, feugiat ac nisi ut, hendrerit hendrerit sem. Sed suscipit nibh in augue aliquet consectetur. Vestibulum viverra diam nunc, at bibendum velit laoreet ut. Proin sit amet metus libero.
      Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent quis sem at massa maximus pulvinar. Vivamus vitae nisl orci. Vestibulum a faucibus magna. Vestibulum ut dui placerat, auctor erat congue, molestie magna. Etiam sem tellus, dignissim et dui in, cursus aliquam massa. Mauris porta condimentum rhoncus. Praesent vitae velit nec mi sodales congue. Aliquam ex nunc, consequat non feugiat sit amet, dictum eget elit. Cras iaculis luctus sodales.
      Praesent in nunc vestibulum, vestibulum enim sed, interdum sapien. Curabitur aliquet dui in lectus rutrum rutrum. Curabitur at lectus sed est ornare molestie. Maecenas ac mollis libero. Mauris pellentesque, magna at pharetra maximus, magna sem sollicitudin mi, ac mattis diam velit at mauris. Quisque rhoncus, mi vel interdum tristique, velit magna facilisis magna, vitae pellentesque augue felis eu orci. Donec eleifend, odio vitae pellentesque egestas, lacus ipsum efficitur purus, sit amet aliquam magna quam ut sapien. Nunc eu magna tempus urna blandit dapibus. Morbi condimentum quam ipsum. Sed eu mattis tortor. Nullam sed dui rutrum, finibus ipsum non, laoreet turpis. Nullam suscipit ullamcorper dolor in aliquet. Quisque varius leo eu lacus elementum, sed gravida lorem faucibus. Ut tincidunt, mauris vitae tincidunt egestas, massa ex sollicitudin est, quis dapibus urna ex at sapien.
      Nullam rhoncus dolor tellus, id pulvinar orci cursus quis. Nullam pretium metus non metus ultrices pulvinar. Integer et ex non sem hendrerit sollicitudin vel quis sem. Maecenas sodales eros ac dui vestibulum, tincidunt molestie ante ultrices. Mauris ullamcorper mattis ex ac imperdiet. Vivamus sed magna neque. Sed dapibus at elit nec bibendum. Aenean vitae imperdiet felis. Duis id feugiat ipsum. Aenean sit amet lorem vel purus elementum congue. Pellentesque ac nisl nisl. Fusce ac quam vitae risus interdum faucibus. Nunc commodo pellentesque elementum. Aliquam erat volutpat. Pellentesque sit amet tempor tellus. Duis finibus quis risus sit amet pretium.
      Proin ante ante, consequat vitae augue eget, sagittis cursus augue. Ut et purus iaculis magna vestibulum congue. Aenean ornare vulputate placerat. Maecenas porttitor, lorem quis egestas volutpat, lacus dui rutrum massa, id sodales lectus libero ut mauris. Mauris gravida diam non enim congue, et ornare nunc condimentum. Aliquam posuere justo sapien, ut eleifend enim feugiat et. Vestibulum sed purus gravida, semper felis eget, rutrum mi.
      Curabitur sit amet maximus nulla. Integer a massa vel ex rhoncus dapibus et a odio. Quisque convallis imperdiet laoreet. Sed mollis sem quis posuere volutpat. Mauris efficitur ipsum non elementum malesuada. Donec eu dapibus odio, sed ornare est. Nulla rutrum magna nibh, id porttitor ante rutrum in. Proin quis ex egestas, suscipit diam sed, luctus diam. Duis consequat posuere erat, id placerat purus consectetur eu. Phasellus porta non ligula non facilisis. Donec rutrum leo in nibh hendrerit, in consectetur leo tincidunt. Mauris ultrices pellentesque nulla in pharetra.
      Morbi sit amet ex nibh. Maecenas porttitor commodo neque nec efficitur. Curabitur viverra lacus id elit ornare elementum. Nunc sed posuere justo. Fusce aliquam sed ex ut ullamcorper. Donec vitae ante quis eros aliquet varius. Ut ac ligula tortor. Morbi finibus pellentesque pulvinar. Vestibulum euismod elementum risus, vitae viverra arcu elementum congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse pharetra, odio vel tincidunt finibus, augue mauris placerat eros, ut porttitor ante purus id velit. Mauris tempor in magna id placerat.</p>
  </div>
</template>
<style lang="scss">
  .uniqueUserPage {
    padding: rem(50);
  }
</style>